version: '3.3'
services:
  example:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8099:80'
    volumes:
      - type: bind
        source: ../..
        target: /app
    networks:
      - example1

  spid-testenv2:
    image: italia/spid-testenv2
    ports:
      - 8088:8088
    restart: always
    volumes:
      - type: bind
        source: ./spid-testenv2
        target: /app/conf
    networks:
      - example2

networks:
  example1:
    driver: bridge
  example2:
    driver: bridge
