language: php

php:
  - 7.0.30
  - 7.1.20
  - 7.2.9

cache:
  directories:
    - $HOME/.composer/cache
    
install:
  - composer install --no-interaction
  - mkdir -p examples/simple/idp_metadata
  - make -C examples/simple/
  - php bin/download_idp_metadata.php ./examples/simple/idp_metadata
  
script:
  - vendor/bin/phpunit --stderr --testdox tests
